//! Information generated by the type checker

use super::{
    DeclKind, Declaration, Function, Num, ResolvedName, ResolvedPath, ScopeGraph, ScopeRef,
    ScopeType, Signature, Type, TypeDef, TypeName, TypeOrStub, ValueKind,
};
use crate::{
    ast::{self, MetaId, ident::Ident},
    ice,
    runtime::RuntimeFunctionRef,
};
use std::collections::btree_map::Entry;
use std::{collections::HashMap, fmt::Debug};

/// The output of the type checker that is used for lowering
#[derive(Clone, Default)]
pub struct TypeInfo {
    /// The unionfind structure that maps type variables to types
    pub(super) unionfind: UnionFind,

    /// All declarations in the program, extracted from the scope graph
    pub(super) scopes: ScopeGraph,

    /// Map from type names to types
    pub(super) types: HashMap<ResolvedName, TypeDef>,

    /// The types we inferred for each Expr
    ///
    /// This might not be fully resolved yet.
    pub(super) expr_types: HashMap<MetaId, Type>,

    /// The fully qualified (and hence unique) name for each identifier.
    pub(super) resolved_names: HashMap<MetaId, ResolvedName>,

    /// Scopes of functions
    pub(super) function_scopes: HashMap<MetaId, ScopeRef>,

    /// The function that is called on each function call
    pub(super) function_calls: HashMap<MetaId, Function>,

    pub(super) rt_functions: HashMap<RuntimeFunctionRef, Signature>,

    /// The ids of all the `Expr::Access` nodes that should be interpreted
    /// as enum variant constructors.
    pub(super) path_kinds: HashMap<MetaId, ResolvedPath>,

    pub(super) diverges: HashMap<MetaId, bool>,

    /// Type for return/accept/reject that it constructs and returns.
    pub(super) return_types: HashMap<MetaId, Type>,
}

impl TypeInfo {
    pub(crate) fn print_scope(&self, scope: ScopeRef) -> String {
        self.scopes.print_scope(scope)
    }

    pub fn get_declaration(&self, name: ResolvedName) -> Declaration {
        self.scopes.get_declaration(name)
    }

    pub fn get_declaration_mut(&mut self, name: ResolvedName) -> &mut Declaration {
        self.scopes.get_declaration_mut(name)
    }

    pub fn resolved_name(&self, x: impl Into<MetaId> + Debug) -> ResolvedName {
        self.resolved_names[&x.into()]
    }

    pub fn type_of(&mut self, x: impl Into<MetaId> + Debug) -> Type {
        self.resolve(&self.expr_types[&x.into()].clone())
    }

    pub fn diverges(&mut self, x: impl Into<MetaId>) -> bool {
        self.diverges[&x.into()]
    }

    pub fn return_type_of(&mut self, x: impl Into<MetaId>) -> Type {
        let ty = self.return_types[&x.into()].clone();
        self.resolve(&ty)
    }

    pub fn function(&self, x: impl Into<MetaId>) -> &Function {
        &self.function_calls[&x.into()]
    }

    pub fn function_scope(&self, x: impl Into<MetaId>) -> ScopeRef {
        self.function_scopes[&x.into()]
    }

    pub fn path_kind(&self, x: impl Into<MetaId>) -> &ResolvedPath {
        &self.path_kinds[&x.into()]
    }

    pub fn full_name(&self, name: &ResolvedName) -> Ident {
        let mut s = self.scopes.print_scope(name.scope);
        s.push('.');
        s.push_str(name.ident.as_str());
        s.into()
    }

    pub fn runtime_function_signature(&self, func_ref: RuntimeFunctionRef) -> Signature {
        self.rt_functions.get(&func_ref).unwrap().clone()
    }

    pub fn is_numeric_type(&mut self, ty: &Type) -> bool {
        self.get_num(ty).is_some()
    }

    pub fn get_num(&mut self, ty: &Type) -> Option<Num> {
        match self.resolve(ty) {
            Type::IVar(_, _) => Some(Num::IVAR),
            Type::FVar(_) => Some(Num::FVAR),
            Type::Name(name) => match self.resolve_type_name(&name) {
                TypeDef::Scalar(num) => Some(num),
                _ => None,
            },
            _ => None,
        }
    }

    pub fn resolve_type_name(&mut self, ty: &TypeName) -> TypeDef {
        match self.scopes.get_declaration(ty.name).kind {
            DeclKind::Type(TypeOrStub::Type(ty)) => ty,
            _ => ice!(),
        }
    }

    pub fn resolve_ref<'a>(&'a self, mut t: &'a Type) -> &'a Type {
        if let Type::Var(x) | Type::IVar(x, _) | Type::RecordVar(x, _) = t {
            t = self.unionfind.find_ref(*x);
        }
        t
    }

    pub fn resolve(&mut self, t: &Type) -> Type {
        let mut t = t.clone();
        if let Type::Var(x) | Type::IVar(x, _) | Type::RecordVar(x, _) | Type::FVar(x) = t {
            t = self.unionfind.find(x).clone();
        }
        t
    }

    pub(crate) fn resolve_name(
        &self,
        scope: ScopeRef,
        ident: &ast::Ident,
        recurse: bool,
    ) -> Option<Declaration> {
        self.scopes.resolve_name(scope, ident, recurse)
    }

    pub(crate) fn parent_module(&self, scope: ScopeRef) -> Option<Declaration> {
        self.scopes.parent_module(scope)
    }

    pub(crate) fn wrap(&mut self, parent: impl Into<ScopeRef>, scope_type: ScopeType) -> ScopeRef {
        self.scopes.wrap(parent, scope_type)
    }
}

impl TypeInfo {
    pub(crate) fn insert_type(
        &mut self,
        scope: ScopeRef,
        ident: &ast::Ident,
        doc: String,
        ty: TypeDef,
    ) -> Result<(), ast::MetaId> {
        let kind = DeclKind::Type(TypeOrStub::Type(ty.clone()));
        let new_scope = self.wrap(scope, ScopeType::Type(**ident));
        let dec = self.insert_decl(scope, ident, kind, doc, |kind| {
            if let DeclKind::Type(TypeOrStub::Stub { num_params }) = kind {
                *num_params == ty.type_name().args.len()
            } else {
                false
            }
        })?;

        if dec.scope.is_none() {
            dec.scope = Some(new_scope);
        }
        Ok(())
    }

    pub(crate) fn insert_module(
        &mut self,
        scope: ScopeRef,
        ident: &ast::Ident,
        doc: String,
        mod_scope: ScopeRef,
    ) -> Result<(), ast::MetaId> {
        let kind = DeclKind::Module;
        let dec = self.insert_decl(scope, ident, kind, doc, |_| false)?;
        dec.scope = Some(mod_scope);
        Ok(())
    }

    pub fn insert_constant(
        &mut self,
        scope: ScopeRef,
        ident: &ast::Ident,
        ty: &Type,
        doc: String,
    ) -> Result<ResolvedName, ()> {
        let name = ResolvedName::new(scope, **ident);
        match self.scopes.declarations.entry(name) {
            Entry::Occupied(_) => Err(()),
            Entry::Vacant(entry) => {
                entry.insert(Declaration {
                    name,
                    kind: DeclKind::Value(ValueKind::Constant, ty.clone()),
                    id: ident.id,
                    doc,
                    scope: None,
                });
                Ok(name)
            }
        }
    }

    pub fn insert_import(
        &mut self,
        scope: ScopeRef,
        id: ast::MetaId,
        name: ResolvedName,
    ) -> Result<(), ast::MetaId> {
        let map = &mut self.scopes.scopes[scope.0].imports;
        match map.entry(name.ident) {
            Entry::Occupied(entry) => Err(entry.get().0),
            Entry::Vacant(entry) => {
                entry.insert((id, name));
                Ok(())
            }
        }
    }

    pub fn decl(
        &mut self,
        scope: ScopeRef,
        ident: &ast::Ident,
        kind: DeclKind,
    ) -> Result<&mut Declaration, ast::MetaId> {
        self.insert_decl(scope, ident, kind, String::new(), |_| false)
    }

    pub fn insert_decl(
        &mut self,
        scope: ScopeRef,
        ident: &ast::Ident,
        kind: DeclKind,
        doc: String,
        update_if: impl Fn(&DeclKind) -> bool,
    ) -> Result<&mut Declaration, ast::MetaId> {
        let name = ResolvedName::new(scope, **ident);
        match self.scopes.declarations.entry(name) {
            Entry::Vacant(entry) => Ok(entry.insert(Declaration {
                name,
                kind,
                id: ident.id,
                scope: None,
                doc,
            })),
            Entry::Occupied(entry) => {
                let old = entry.into_mut();
                if update_if(&old.kind) {
                    old.kind = kind;
                    Ok(old)
                } else {
                    Err(old.id)
                }
            }
        }
    }
}

/// A simple unionfind data structure
///
/// A [`usize`] is mapped to a [`Type`], if that type is a type variable,
/// we recurse to find what it maps to. On its way out of the call stack
/// it sets each type it traversed to the final type it found to limit
/// traversal in a subsequent query.
///
/// A mapping from a type var to itself means that it is not set.
#[derive(Clone, Debug, Default)]
pub struct UnionFind {
    inner: Vec<Type>,
}

impl UnionFind {
    /// Find the type corresponding to a type var
    pub fn find(&mut self, index: usize) -> Type {
        match &self.inner[index] {
            Type::Var(i) | Type::IVar(i, _) | Type::FVar(i) | Type::RecordVar(i, _)
                if *i != index =>
            {
                let new_t = self.find(*i);
                self.inner[index] = new_t.clone();
                new_t
            }
            t => t.clone(),
        }
    }

    /// Generate a new type var
    pub fn fresh(&mut self, f: impl FnOnce(usize) -> Type) -> Type {
        let n = self.inner.len();
        let t = f(n);
        self.inner.push(t.clone());
        t
    }

    /// Set value of a type var
    pub fn set(&mut self, index: usize, t: Type) {
        self.inner[index] = t;
    }

    pub fn find_ref(&self, index: usize) -> &Type {
        match &self.inner[index] {
            Type::Var(i) | Type::IVar(i, _) | Type::FVar(i) | Type::RecordVar(i, _)
                if *i != index =>
            {
                self.find_ref(*i)
            }
            t => t,
        }
    }
}
