[package]
name = "bevy_lang"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.6"
bevy = "0.16"

[[bench]]
name = "simple"
harness = false

[dependencies]
bevy_reflect = "0.16.1"
bevy_ptr = "0.16.1"
thiserror = "2.0.12"
indexmap = "2.9.0"
rustc-hash = "2.1.1"
hashbrown = "0.15.4"
chumsky = { version = "1.0.0-alpha.8", features = ["pratt", "lexical-numbers"] }
serde = { version = "1.0.219", optional = true }

[features]
default = ["serde"]
serde = ["dep:serde"]
