//! This example shows how to create a custom render pass that runs after the main pass
//! and reads the texture generated by the main pass.
//!
//! The example shader is a very simple implementation of chromatic aberration.
//! To adapt this example for 2D, replace all instances of 3D structures (such as `Core3D`, etc.) with their corresponding 2D counterparts.
//!
//! This is a fairly low level example and assumes some familiarity with rendering concepts and wgpu.

use bevy::{
    core_pipeline::{Core3d, Core3dSystems, FullscreenShader},
    image::BevyDefault,
    prelude::*,
    render::{
        RenderApp,
        extract_component::{
            ComponentUniforms, DynamicUniformIndex, ExtractComponent, ExtractComponentPlugin,
            UniformComponentPlugin,
        },
        render_resource::{
            binding_types::{sampler, texture_2d, uniform_buffer},
            *,
        },
        renderer::{RenderContext, RenderDevice, ViewQuery},
        view::{PostProcessWrite, ViewTarget, ViewUniform, ViewUniformOffset, ViewUniforms},
    },
};

// This is the component that will get passed to the shader
#[derive(Component, Default, Clone, Copy, ExtractComponent, ShaderType)]
pub struct GridSettings {
    pub size: Vec2,
    pub offset_y: f32,
    pub padding: f32,
}

/// This example uses a shader source file from the assets subdirectory
const SHADER_ASSET_PATH: &str = "shaders/grid.wgsl";

pub fn plugin(app: &mut App) {
    app.add_plugins(GridPlugin).add_systems(PostStartup, setup);
}

fn setup(mut commands: Commands, camera: Single<Entity, With<Camera3d>>) {
    commands.entity(camera.into_inner()).insert(GridSettings {
        size: Vec2::splat(1.0),
        offset_y: 2.0,
        padding: 0.0,
    });
}

pub struct GridPlugin;

impl Plugin for GridPlugin {
    fn build(&self, app: &mut App) {
        app.add_plugins((
            ExtractComponentPlugin::<GridSettings>::default(),
            UniformComponentPlugin::<GridSettings>::default(),
        ));

        let Some(render_app) = app.get_sub_app_mut(RenderApp) else {
            return;
        };

        // render_app.add_render_graph_node::<ViewNodeRunner<GridNode>>(Core3d, GridLabel);
        // render_app.add_render_graph_edges(Core3d, (Node3d::Tonemapping, GridLabel, End));

        render_app.add_systems(
            Core3d,
            grid_node_pass
                .after(bevy::core_pipeline::tonemapping::tonemapping)
                // .before(Node3d::EndMainPassPostProcessing)
                .in_set(Core3dSystems::PostProcess),
        );
    }

    fn finish(&self, app: &mut App) {
        let Some(render_app) = app.get_sub_app_mut(RenderApp) else {
            return;
        };

        render_app.init_resource::<GridPipeline>();
    }
}

fn grid_node_pass(
    //_graph: &mut RenderGraphContext,
    mut render_context: RenderContext,
    world: &World,
    view: ViewQuery<(
        &ViewTarget,
        &GridSettings,
        &DynamicUniformIndex<GridSettings>,
        &ViewUniformOffset,
    )>,
) {
    let (view_target, _settings, settings_index, view_uniform_offset) = view.into_inner();

    let grid_pipeline = world.resource::<GridPipeline>();
    let pipeline_cache = world.resource::<PipelineCache>();
    let settings_uniforms = world.resource::<ComponentUniforms<GridSettings>>();
    let view_uniforms = world.resource::<ViewUniforms>();

    let pipeline = pipeline_cache.get_render_pipeline(grid_pipeline.pipeline_id);
    let settings = settings_uniforms.uniforms().binding();
    let views = view_uniforms.uniforms.binding();

    let Some(((settings, views), pipeline)) = settings.zip(views).zip(pipeline) else {
        return;
    };

    let PostProcessWrite {
        source,
        destination,
        ..
    } = view_target.post_process_write();

    let bind_group = render_context.render_device().create_bind_group(
        "grid_bind_group",
        &grid_pipeline.layout,
        &BindGroupEntries::sequential((
            source,
            &grid_pipeline.sampler,
            settings.clone(),
            views.clone(),
        )),
    );

    let dyn_indices = &[settings_index.index(), view_uniform_offset.offset];

    let mut render_pass = render_context.begin_tracked_render_pass(RenderPassDescriptor {
        label: Some("grid_pass"),
        color_attachments: &[Some(RenderPassColorAttachment {
            view: destination,
            resolve_target: None,
            ops: Operations::default(),
            depth_slice: None,
        })],
        depth_stencil_attachment: None,
        timestamp_writes: None,
        occlusion_query_set: None,
        multiview_mask: None,
    });

    render_pass.set_render_pipeline(pipeline);
    render_pass.set_bind_group(0, &bind_group, dyn_indices);
    render_pass.draw(0..3, 0..1);

    //Ok(())
}

#[derive(Resource)]
struct GridPipeline {
    layout: BindGroupLayout,
    sampler: Sampler,
    pipeline_id: CachedRenderPipelineId,
}

impl FromWorld for GridPipeline {
    fn from_world(world: &mut World) -> Self {
        let render_device = world.resource::<RenderDevice>();

        let entries = BindGroupLayoutEntries::sequential(
            ShaderStages::FRAGMENT,
            (
                texture_2d(TextureSampleType::Float { filterable: true }),
                sampler(SamplerBindingType::Filtering),
                uniform_buffer::<GridSettings>(true),
                uniform_buffer::<ViewUniform>(true),
            ),
        );

        let layout = render_device.create_bind_group_layout("grid_bind_group_layout", &entries);

        let sampler = render_device.create_sampler(&SamplerDescriptor::default());
        let shader = world.load_asset(SHADER_ASSET_PATH);

        let hdr = true;

        let fullscreen_shader = world.resource::<FullscreenShader>().clone();
        let pipeline_cache = world.resource_mut::<PipelineCache>();

        let pipeline_id = pipeline_cache.queue_render_pipeline(RenderPipelineDescriptor {
            label: Some("grid_pipeline".into()),
            layout: vec![BindGroupLayoutDescriptor {
                label: default(),
                entries: entries.to_vec(),
            }],
            vertex: fullscreen_shader.to_vertex_state(),
            fragment: Some(FragmentState {
                shader,
                shader_defs: vec![],
                entry_point: Some("fragment".into()),
                targets: vec![Some(ColorTargetState {
                    format: if hdr {
                        ViewTarget::TEXTURE_FORMAT_HDR
                    } else {
                        TextureFormat::bevy_default()
                    },
                    blend: None,
                    write_mask: ColorWrites::ALL,
                })],
            }),
            primitive: PrimitiveState::default(),
            depth_stencil: None,
            multisample: MultisampleState::default(),
            zero_initialize_workgroup_memory: false,
            immediate_size: 0,
        });

        Self {
            layout,
            sampler,
            pipeline_id,
        }
    }
}
